### ISSUE TITLE
Phrase tronquée dans une note

### ISSUE THREAD

**Issue by guillett** [MattiSG/livre-blanc-communs-numeriques#3]
Sur la page Docker

https://communs.mattischneider.fr/6-annexes/2-exemples/3-docker.html#fn_25

https://github.com/MattiSG/livre-blanc-communs-numeriques/blame/master/6-annexes/2-exemples/3-docker.md#L38

**Comment by MattiSG** [comment]
Merci beaucoup ! Cette analyse de Docker était une contribution tierce. J'ai fait apparaître cet aspect, supprimé la note tronquée, et ai corrigé d'autres formulations au passage 🙂
